### ISSUE TITLE
fxh files for common functions

### ISSUE THREAD

**Issue by elliotwoods** [mrvux/dx11-vvvv#143]
it'd be great to have a library of common shader functions available by default (e.g. Perlin, Simplex, etc)

**Comment by mrvux** [comment]
I would not add custom fxh as is, since most users handle their shaders differently, also that means functions would also need versioning, I prefer to have users to maintain their patch/shaders the way they want. I like the idea in some way but it's out of the scope of the core (could definitely be a separate repository).

As a side note, you can set system includes path in the vvvv.exe.config file if you want (single folder for now), like:

<appSettings>
    <add key="SysIncludePath" value="[path to your includes]" />
  </appSettings>

One of those little undocumented features ;)
