### ISSUE TITLE
Kinect2 Depth node: Page Faults

### ISSUE THREAD

**Issue by circuitb** [mrvux/dx11-vvvv#204]
hi,
just found a strange behaviour with the kinect2 Depth node:
when it's present and Enabled in a patch  the "Page faults" column in the task manager
start to increase after a few hours of use i've something like 30 000 000 in that column!!!
not sure it's a real issue because even if  the gui start to lag a little bit 
and vvvv need more than 60 seconds to close itself it's still working...
any ideas, recommendations?
thanks

**Comment by mediadog** [comment]
Wow that's weird - I just checked a system that's been running for 19 days and vvvv.exe has 2 billion page faults; it seems to be running about 10,000 per second.  I can notice no decline in performance, but I have noticed sometimes it will hang shutting down - maybe I just wasn't waiting long enough...  I am using the Kinect2 plugins build by noobusdeer.

**Comment by mrvux** [comment]
From what I seen, page fault increases a lot in any case when using Kinect2 in general. I had a look at standalone examples and they show the same behaviour (steady increase)
After if those are "Soft page faults" which seems likely since you say you don't noticed performance drops, it's not always a problem.
4v taking a lot of time to close seems another issue, what is your memory usage in that case?

**Comment by circuitb** [comment]
right vux the closing time thing is due to a physical memory overload from ableton+vvvv

**Comment by mrvux** [comment]
Ok will just close this one, since from what I looked it's not related to implementation (as all samples do exactly the same)
