### ISSUE TITLE
New node interface

### ISSUE THREAD

**Issue by mrvux** [mrvux/dx11-vvvv#229]
All interfaces that use IPluginIO :
- IDX11RendererProvider
- IDX11LayerProvider
- IDX11ResourceProvider

And associated delegate node are now obsolete, they are replaced by : same name, but with host suffix).

For next release, those new interfaces will not be implemented in core (as I don't want selection inside the traversal), but old interfaces are already marked as obsolete.

After next release those old interfaces will be removed right away, and nodes will use the new ones.

This is not a huge change, but a breaking change which is necessary in order to allow to access dx11 nodes in a multi threaded way, there can't be exceptions in nodes hence why no way to provide backwards compatibility.

Moving toward new interface is easy tho, just rename interface and remove IPluginIO parameter, so it will take minutes to sort out (but yes it will need a recompile).

**Comment by tebjan** [comment]
:+1:

**Comment by microdee** [comment]
ok i replaced every provider interface with its host equivalent and bad news for some reason there's a HUGE overhead on spreading layers.
i had a scene with 200 cubes not instanced because I was lazy. Compiled the repo with the old provider interfaces it was running 110 fps, after compiled with the new host interfaces not changing anything else, same patch without any modification 12 fps.
i suspect spreading the layers or something around them because 1st: that patch renderingwise was simple phongdirectional and nothing else and 2nd: other patches with only 1-4 slices were running fine or the difference was not at all noticable.

**Comment by mrvux** [comment]
Not sure how you compiled it, as for now Host interface is not picked up by graph builder, but I already got it running in local branch and there's no perf difference (after all it's just one less parameter).

One potential problem is that you have still some exception triggered, which slows down a lot when running under a debugger.

**Comment by microdee** [comment]
well replaced providers to hosts (except definition obviously) then set build configuration to release/x64 then pressed build button. can you make a branch where you're using hosts where it's suitable? maybe i messed up something during replacing.

**Comment by mrvux** [comment]
Ok I pushed pluginio branch, guess you had something wrong around (also graph traversal needed couple more changes than just replace I would suspect somehow the destroy part was triggered every frame ;) 

Did a perf test on laptop, 50 fps for 8k spheres in both cases, so there's 0 difference (which is as expected). 
So that's a pretty good start :)

**Comment by microdee** [comment]
nnnnniiiice thanks santa vux!
