### ISSUE TITLE
DirectWrite text doesn't display

### ISSUE THREAD

**Issue by microdee** [mrvux/dx11-vvvv#232]
directwrite text doesn't seem to display after the .net 4.5 migration it was fine when dx11 was targeting 4.0. Also VVVV.DX11.Nodes.Text can't compile here in VS 2015 complaining about framework version mismatch and missing namespaces, that might cause this problem however it's beyond my comprehension to fix it :(

**Comment by mediadog** [comment]
The Text (DX11) node in the 24.05.15 x86 release is coming up red on two machines here that have new clean Win7 Enterprise x64 installations (with all critical updates).  vvvv setup is showing all green lights for both 33.7 and 34.2.  I initially thought the problem was fixed by having the x64 vvvv version installed too, but that is not the case.  Could this be related?

**Comment by mediadog** [comment]
Never mind about the red test nodes - it was a Stupid User Trick.  I had copied over libs I had built for testing and forgot they were there and they got copied over to the new machine.

**Comment by mrvux** [comment]
You still need to have the visual c++ 2013 platform profile installed to build using 2015, I guess I'll upgrade that at some point (ideally wrapping the text library sharpdx style so no need for a c++ build).

**Comment by mrvux** [comment]
In latest build text is now built against VS 2015
