### ISSUE TITLE
kinect2 nodes  

### ISSUE THREAD

**Issue by circuitb** [mrvux/dx11-vvvv#291]
hello @mrvux @id144 ,
nice to see this big dx11 update!

i get this message : unable to load libz3.dll...and  vvvv34.2 x64 crash!
addding back  libz3.dll from a previous install solve the problem!

by the way1
still no luck with Prepose + GestureStatus nodes (gesture is red... Test.app looks good to me)
see attached
[prepose.zip](https://github.com/mrvux/dx11-vvvv/files/757355/prepose.zip)

by the way2
what's the purpose of the BodyIndex node? i try to pipet the output texture to find something but no luck also ;)

thanks
ciao!

**Comment by mrvux** [comment]
https://github.com/mrvux/dx11-vvvv/commit/626778442ccc819e55a7584993a6c72a9991ac6a
https://github.com/mrvux/dx11-vvvv/commit/a8e6941b8bde2387f0dc2759182e48dc40f5e6db

Sort the library copy for now

About prepose, sorry I mixed up, the node expects the code itself, not the file name (so you need a reader file on top).

Updated pin names in above commits

BodyIndex is a R8_Uint texture, which contains raw body index (eg: 0-5 for player and 255 for "no user").
Since it's a Uint, view, you need Texture2d<uint> in shader ot access it, and samplers to not work on it (you need to use load).

If used in order to build more complex maps or user trackings in compute basically.

Hope it all helps :)

**Comment by mrvux** [comment]
https://github.com/mrvux/dx11-vvvv/releases/tag/1.0.4-alpha

Should be all sorted now, please close if it does work as expected

**Comment by circuitb** [comment]
thanks Vux,
All good!!
closing..
