### ISSUE TITLE
Quad (DX11.Layer) throws exception if started with Nil transform

### ISSUE THREAD

**Issue by mediadog** [mrvux/dx11-vvvv#328]
If a patch loads with a Quad being given a Nil transform, it throws an exception until it is given a transform input.  Then giving it a Nil again turns the Quad off with no exception, as expected.  This is in 1.1, worked as expected in previous versions.

Steps to reproduce:
1) Create a Quad (DX11.layer) node
2) Create a Nil (Node) node
3) Link the Nil output to the Quad Transform input pin
4) Hook the Quad to a Renderer, exceptions start
5) Delete link from Nil node, exceptions stop, Quad appears
6) Reconnect Nil node, no exceptions, Quad disappears

**Comment by mediadog** [comment]
Same thing happens with a Nil Color.

**Comment by mrvux** [comment]
This should already be fixed in 
https://github.com/mrvux/dx11-vvvv/commit/c751f15b456e442a8d1a726230a02894a67f1e34

If you need a build with that fix, look here (same as current version in vvvv website with that fix on top + another small improvement, so no big changes)

https://ci.appveyor.com/project/mrvux/dx11-vvvv/build/artifacts

**Comment by mediadog** [comment]
Ayup, that fixes it.  Thanks, that was a show-stopper!
