### ISSUE TITLE
Access TexturesArrays in Texture FX

### ISSUE THREAD

**Issue by catvvvveasel** [mrvux/dx11-vvvv#84]
Would be nice if we could access arrays in fx, its doesnt seem to work at the moment!

**Comment by elliotwoods** [comment]
just came across this one. 
it seems whenever I sample from the `Texture2DArray` within a `.tfx` I just get white.
It's working fine inside `.fx` (actually, had to restart VVVV at one point to get it working, because something didn't get updated when I switched the input from `Texture2D []` to `Texture2DArray`).
